<?xml version="1.0" encoding="UTF-8"?>


<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE team [

<!ELEMENT team (sport)>
<!ELEMENT sport (football)>
<!ELEMENT football (coach, players)>
<!ELEMENT  coach (#PCDATA)>
<!ELEMENT  players (#PCDATA, p*)>
<!ELEMENT  p (#PCDATA)>

]>

<team>
    <sport>
        <football> 
              <coach> the coach </coach>
                <players>Here is the players 
                
                    <p>Sam</p>
                    <p>ronaldo</p>
                    <p>pele</p>
                    <p>messi</p>
                    <p>neymar</p>
                    <p>ali</p>
                    <p>omar</p>
                    <p>amr</p>
                    <p>wael</p>
                    <p>ziad</p>
                
                
                </players>    
        
        </football>
        
    </sport>

    
</team>



